spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Surendra7642/configuration_properties
          clone-on-start: true
management:
  security:
    enabled: false
server:
    port: 8081